"use client";

import { LanguageToggle, useLanguage } from "./components/language";
import { reviewerVenues } from "./publications";

const news = [
  { date: "May 2026", dateZh: "2026年5月", text: "See What Matters is accepted by ICML 2026.", textZh: "See What Matters 被 ICML 2026 接收。" },
  { date: "June 2025", dateZh: "2025年6月", text: "FusionNet wins 1st place in the NTIRE 2025 Low-Light Enhancement challenge.", textZh: "FusionNet 获得 NTIRE 2025 低光图像增强赛道冠军。" },
  { date: "June 2025", dateZh: "2025年6月", text: "HVI is accepted by CVPR 2025 and released as an open-source implementation.", textZh: "HVI 被 CVPR 2025 接收，并发布开源实现。" },
  { date: "June 2025", dateZh: "2025年6月", text: "Flow-Guided HDR Restoration wins 2nd place in the NTIRE 2025 Burst HDR Restoration challenge.", textZh: "流引导 HDR 恢复工作获得 NTIRE 2025 连拍 HDR 恢复赛道第二名。" },
  { date: "March 2025", dateZh: "2025年3月", text: "NWPU Computer School featured my CVPR research journey and low-light enhancement work.", textZh: "西北工业大学计算机学院报道了我的 CVPR 研究经历与弱光图像增强工作。", link: "https://jsj.nwpu.edu.cn/info/1600/25255.htm" },
  { date: "June 2024", dateZh: "2024年6月", text: "DiffLight receives an oral presentation and 4th place in the NTIRE 2024 Low-Light Enhancement challenge.", textZh: "DiffLight 入选 NTIRE 2024 口头报告，并获得低光图像增强赛道第四名。" },
];

export default function Home() {
  const { language } = useLanguage();
  const zh = language === "zh";
  const nav = zh
    ? ["首页", "论文", "教育经历", "实习经历", "审稿", "荣誉", "项目", "联系"]
    : ["Homepage", "Publications", "Education", "Internship", "Reviewing", "Honors", "Projects", "Contact"];

  return (
    <main>
      <header className="top-nav"><nav className="nav-inner" aria-label="Primary navigation"><a href="#home">{nav[0]}</a><a href="/publication">{nav[1]}</a><a href="#education">{nav[2]}</a><a href="#internship">{nav[3]}</a><a href="#reviewing">{nav[4]}</a><a href="#awards">{nav[5]}</a><a href="/project">{nav[6]}</a><a href="#contact">{nav[7]}</a><LanguageToggle /></nav></header>
      <div className="site-wrap" id="home">
        <section className="hero-card profile-section"><aside className="profile-sidebar"><img className="profile-photo" src="https://avatars.githubusercontent.com/u/113850295?v=4" alt="Yixu Feng" /><p className="eyebrow">{zh ? "研究 · 系统 · 视觉" : "RESEARCH · SYSTEMS · VISION"}</p><h1>Yixu Feng</h1><p className="name-cn">冯宜湑</p><p className="affiliation">{zh ? "悉尼大学" : "The University of Sydney"}</p><p className="role">{zh ? "计算机科学与技术博士生" : "Ph.D. student in Computer Science and Technology"}</p><p className="location">{zh ? "悉尼，澳大利亚" : "Sydney, Australia"}</p><div className="contact-links" id="contact"><a href="mailto:fediory@gmail.com">{zh ? "邮箱" : "Email"}</a><a href="https://scholar.google.com/citations?user=WljJ2HUAAAAJ" target="_blank" rel="noreferrer">{zh ? "谷歌学术" : "Google Scholar"}</a></div></aside><div className="profile-main"><p className="hero-kicker">{zh ? "具身智能 · VLA 系统 · 图像增强" : "Embodied AI · VLA systems · Image enhancement"}</p><h2>{zh ? "构建面向真实交互的高效视觉智能。" : "Building efficient visual intelligence for real-world interaction."}</h2><p>{zh ? <>我目前是<a href="https://www.sydney.edu.au/" target="_blank" rel="noreferrer">悉尼大学</a>计算机科学与技术博士生，导师为<a href="http://www.changxu.xyz/" target="_blank" rel="noreferrer">Chang Xu 教授</a>。</> : <>I am a Ph.D. student at <a href="https://www.sydney.edu.au/" target="_blank" rel="noreferrer">The University of Sydney</a>, advised by <a href="http://www.changxu.xyz/" target="_blank" rel="noreferrer">Prof. Chang Xu</a>.</>}</p><p>{zh ? "我的研究聚焦具身智能，尤其关注 VLA/WAM 模型的架构、推理与加速，同时研究弱光图像增强算法和机器学习。" : "My research focuses on embodied AI, especially the architecture, reasoning, and acceleration of Vision-Language-Action (VLA) and World Action Model (WAM) systems. I also work on low-light image enhancement and machine learning."}</p><div className="hero-actions"><a className="button button-primary" href="/publication">{zh ? "查看论文 ↗" : "Explore publications ↗"}</a><a className="button" href="/project">{zh ? "项目 ↗" : "Projects ↗"}</a><a className="button" href="https://github.com/Fediory" target="_blank" rel="noreferrer">GitHub ↗</a></div></div></section>
        <section className="section" id="news"><div className="section-heading"><p className="eyebrow">{zh ? "01 · 动态" : "01 · UPDATES"}</p><h2>{zh ? "新闻" : "News"}</h2></div><div className="news-list">{news.map((item) => <div className="news-item" key={item.date + item.text}><span>{zh ? item.dateZh : item.date}</span><p>{item.link ? <a href={item.link} target="_blank" rel="noreferrer">{zh ? item.textZh : item.text} ↗</a> : (zh ? item.textZh : item.text)}</p></div>)}</div></section>
        <section className="section" id="reviewing"><div className="section-heading"><p className="eyebrow">{zh ? "02 · 学术服务" : "02 · SERVICE"}</p><h2>{zh ? "学术审稿" : "Academic Reviewing"}</h2></div><p className="section-intro">{zh ? "我为计算机视觉、多媒体、机器学习和人工智能系统领域的顶级会议与期刊提供审稿服务。" : "I serve as a reviewer for leading venues across computer vision, multimedia, machine learning, and AI systems."}</p><div className="review-grid">{reviewerVenues.map((venue) => <div className="review-chip" key={venue}><span className="chip-dot" />{venue}</div>)}</div></section>
        <section className="section" id="education"><div className="section-heading"><p className="eyebrow">{zh ? "03 · 教育经历" : "03 · TRAINING"}</p><h2>{zh ? "教育经历" : "Education"}</h2></div><div className="timeline-row"><span>{zh ? "2025.10 – 至今" : "2025.10 – Present"}</span><div><strong>{zh ? "计算机科学与技术哲学博士" : "Ph.D. in Computer Science and Technology"}</strong><p>{zh ? <>悉尼大学 · 导师：<a href="http://www.changxu.xyz/" target="_blank" rel="noreferrer">Chang Xu</a></> : <>The University of Sydney · Advisor: <a href="http://www.changxu.xyz/" target="_blank" rel="noreferrer">Chang Xu</a></>}</p><p>{zh ? "研究方向：具身智能，VLA/WAM 模型的架构、推理与加速，图像增强算法和机器学习。" : "Research: Embodied AI, VLA/WAM architecture, reasoning and acceleration, image enhancement, and machine learning."}</p></div></div><div className="timeline-row"><span>{zh ? "2021.09 – 2025.06" : "2021.09 – 2025.06"}</span><div><strong>{zh ? "计算机科学与技术工学学士" : "B.Eng. in Computer Science and Technology"}</strong><p>{zh ? "西北工业大学 · 康继昌智能系统拔尖班" : "Northwestern Polytechnical University · Jichang Kang Intelligent Systems Elite Class"}</p></div></div></section>
        <section className="section" id="internship"><div className="section-heading"><p className="eyebrow">{zh ? "04 · 实习经历" : "04 · EXPERIENCE"}</p><h2>{zh ? "实习经历" : "Internship"}</h2></div><div className="timeline-row"><span>{zh ? "2025.10 – 2026.04" : "2025.10 – 2026.04"}</span><div><strong>{zh ? "科研实习生 · 杭州星衍智能 Stellar Edge AI" : "Research Intern · Stellar Edge AI, Hangzhou"}</strong><p>{zh ? "面向人形机器人及 Franka/SO100 机械臂搭建 VLA 模型数据采集、微调和真机部署流水线，设计剪枝与量化方案，将端到端延迟降低约 40%。" : "Built an end-to-end VLA deployment pipeline for humanoid robots and Franka/SO100 arms; designed pruning and quantization methods that reduced end-to-end latency by about 40%."}</p></div></div><div className="timeline-row"><span>{zh ? "2024.07 – 2024.08" : "2024.07 – 2024.08"}</span><div><strong>{zh ? "图形算法实习生 · 中金汇安（北京）科技有限公司" : "Graphics Algorithm Intern · Zhongjin Huian (Beijing) Technology Co., Ltd."}</strong><p>{zh ? "负责银行柜台监控视频的实时流分析与低光增强，在边缘设备上实现 30fps 处理，使低光条件下违规检测准确率提升超过 15%。" : "Developed low-light enhancement and real-time video analysis modules for bank-counter surveillance, improving violation detection accuracy by more than 15%."}</p></div></div><div className="timeline-row"><span>{zh ? "2024.01 – 2024.02" : "2024.01 – 2024.02"}</span><div><strong>{zh ? "调度算法架构师助理 · 北京航臻科技有限公司" : "Scheduling Algorithm Architect Assistant · Beijing Hangzhen Technology Co., Ltd."}</strong><p>{zh ? "北京，中国" : "Beijing City, China"}</p><p>{zh ? "协助智能生产线调度算法架构师从架构设计和算法优化角度引入 AI 大模型。" : "Assisted the intelligent production-line scheduling algorithm architect in introducing AI large models for architecture design and algorithm optimization."}</p></div></div></section>
        <section className="section" id="awards"><div className="section-heading"><p className="eyebrow">{zh ? "05 · 荣誉奖励" : "05 · RECOGNITION"}</p><h2>{zh ? "荣誉与奖励" : "Honors and Awards"}</h2></div><ul className="award-list">{(zh ? ["2024 年全国大学生计算机系统能力大赛操作系统设计赛（全国）OS 内核实现赛道一等奖（队长）", "第二届 CrowdOS 开源挑战赛一等奖（队长）", "第七届全国大学生计算机系统能力大赛“龙芯杯”三等奖（队长）", "第十五届“挑战杯”陕西省大学生课外学术科技作品竞赛特等奖（队员）"] : ["2024 National Collegiate Computer System Capability Contest – OS Kernel Implementation Track, First Prize (Team Leader)", "The 2nd CrowdOS Open-Source Challenge, First Prize (Team Leader)", "The 7th National Collegiate Computer System Capability Contest – “Loongson Cup”, Third Prize (Team Leader)", "The 15th “Challenge Cup” Shaanxi Provincial Academic & Technology Competition, Grand Prize (Team Member)"]).map((award) => <li key={award}>{award}</li>)}</ul></section>
      </div><footer className="footer"><span>© {new Date().getFullYear()} Yixu Feng (冯宜湑)</span><span>{zh ? "最后更新：2026" : "Last updated 2026"}</span></footer>
    </main>
  );
}
