import { reviewerVenues } from "./publications";

const news = [
  { date: "2026", text: "See What Matters is accepted by ICML 2026." },
  { date: "2025", text: "FusionNet ranks first in the CVPR 2025 NTIRE Low-Light Enhancement track." },
  { date: "2025", text: "HVI is accepted by CVPR 2025 and released as an open-source implementation." },
  { date: "2025", text: "FusionNet wins 1st place in the NTIRE 2025 Low-Light Enhancement challenge." },
  { date: "2025", text: "Flow-Guided HDR Restoration wins 2nd place in the NTIRE 2025 Burst HDR Restoration challenge." },
  { date: "2024", text: "DiffLight receives an oral presentation and 4th place in the NTIRE 2024 Low-Light Enhancement challenge." },
  { date: "2025", text: "NWPU Computer School featured my CVPR research journey and low-light enhancement work.", link: "https://jsj.nwpu.edu.cn/info/1600/25255.htm" },
];

export default function Home() {
  return (
    <main>
      <header className="top-nav"><nav className="nav-inner" aria-label="Primary navigation"><a href="#home">Homepage</a><a href="/publication">Publications</a><a href="#education">Education</a><a href="#internship">Internship</a><a href="#reviewing">Reviewing</a><a href="#awards">Honors</a><a href="#projects">Projects</a><a href="#contact">Contact</a></nav></header>
      <div className="site-wrap" id="home">
        <section className="hero-card profile-section"><aside className="profile-sidebar"><img className="profile-photo" src="https://avatars.githubusercontent.com/u/113850295?v=4" alt="Yixu Feng" /><p className="eyebrow">RESEARCH · SYSTEMS · VISION</p><h1>Yixu Feng</h1><p className="name-cn">冯宜湑</p><p className="affiliation">The University of Sydney</p><p className="role">Ph.D. student in Computer Science and Technology</p><p className="location">Sydney, Australia</p><div className="contact-links" id="contact"><a href="mailto:fediory@gmail.com">Email</a><a href="https://github.com/Fediory" target="_blank" rel="noreferrer">GitHub</a><a href="https://scholar.google.com/citations?user=WljJ2HUAAAAJ" target="_blank" rel="noreferrer">Google Scholar</a></div></aside><div className="profile-main"><p className="hero-kicker">Embodied AI · VLA systems · Image enhancement</p><h2>Building efficient visual intelligence for real-world interaction.</h2><p>I am a Ph.D. student at <a href="https://www.sydney.edu.au/" target="_blank" rel="noreferrer">The University of Sydney</a>, advised by <a href="https://scholar.google.com/citations?user=N4F_3eoAAAAJ" target="_blank" rel="noreferrer">Prof. Chang Xu</a>.</p><p>My research focuses on embodied AI, especially the architecture, reasoning, and acceleration of Vision-Language-Action (VLA) and World Action Model (WAM) systems. I also work on low-light image enhancement and machine learning.</p><div className="hero-actions"><a className="button button-primary" href="/publication">Explore publications ↗</a><a className="button" href="https://github.com/Fediory" target="_blank" rel="noreferrer">GitHub ↗</a></div></div></section>
        <section className="section" id="news"><div className="section-heading"><p className="eyebrow">01 · UPDATES</p><h2>News</h2></div><div className="news-list">{news.map((item) => <div className="news-item" key={item.date + item.text}><span>{item.date}</span><p>{item.link ? <a href={item.link} target="_blank" rel="noreferrer">{item.text} ↗</a> : item.text}</p></div>)}</div></section>
        <section className="section" id="reviewing"><div className="section-heading"><p className="eyebrow">02 · SERVICE</p><h2>Academic Reviewing</h2></div><p className="section-intro">I serve as a reviewer for leading venues across computer vision, multimedia, machine learning, and AI systems.</p><div className="review-grid">{reviewerVenues.map((venue) => <div className="review-chip" key={venue}><span className="chip-dot" />{venue}</div>)}</div></section>
        <section className="section" id="education"><div className="section-heading"><p className="eyebrow">03 · TRAINING</p><h2>Education</h2></div><div className="timeline-row"><span>2025.10 – Present</span><div><strong>Ph.D. in Computer Science and Technology</strong><p>The University of Sydney · Advisor: Chang Xu</p><p>Research: Embodied AI, VLA/WAM architecture, reasoning and acceleration, image enhancement, and machine learning.</p></div></div><div className="timeline-row"><span>2021.09 – 2025.06</span><div><strong>B.Eng. in Computer Science and Technology</strong><p>Northwestern Polytechnical University · Jichang Kang Intelligent Systems Elite Class</p></div></div></section>
        <section className="section" id="internship"><div className="section-heading"><p className="eyebrow">04 · EXPERIENCE</p><h2>Internship</h2></div><div className="timeline-row"><span>2025.10 – 2026.04</span><div><strong>Research Intern · Stellar Edge AI, Hangzhou</strong><p>Built an end-to-end VLA deployment pipeline for humanoid robots and Franka/SO100 arms; designed pruning and quantization methods that reduced end-to-end latency by about 40%.</p></div></div><div className="timeline-row"><span>2024.07 – 2024.08</span><div><strong>Graphics Algorithm Intern · Zhongjin Huian (Beijing) Technology Co., Ltd.</strong><p>Developed low-light enhancement and real-time video analysis modules for bank-counter surveillance, improving violation detection accuracy by more than 15%.</p></div></div><div className="timeline-row"><span>2024.01 – 2024.02</span><div><strong>Scheduling Algorithm Architect Assistant · Beijing Hangzhen Technology Co., Ltd.</strong><p>Beijing City, China</p><p>Assisted the intelligent production-line scheduling algorithm architect in introducing AI large models for architecture design and algorithm optimization.</p></div></div></section>
        <section className="section" id="awards"><div className="section-heading"><p className="eyebrow">05 · RECOGNITION</p><h2>Honors and Awards</h2></div><ul className="award-list"><li>2024 National Collegiate Computer System Capability Contest – OS Kernel Implementation Track, First Prize (Team Leader)</li><li>The 2nd CrowdOS Open-Source Challenge, First Prize (Team Leader)</li><li>The 7th National Collegiate Computer System Capability Contest – “Loongson Cup”, Third Prize (Team Leader)</li><li>The 15th “Challenge Cup” Shaanxi Provincial Academic &amp; Technology Competition, Grand Prize (Team Member)</li></ul></section>
        <section className="section" id="projects"><div className="section-heading"><p className="eyebrow">06 · OPEN SOURCE</p><h2>Projects</h2></div><div className="project-grid"><div className="project-card"><span className="project-index">01</span><strong>Grid-Sampler</strong><p>Efficient visual token resampling for VLA systems.</p><div className="project-actions"><a href="https://github.com/Fediory/Grid-Sampler" target="_blank" rel="noreferrer">Project ↗</a><a href="https://fediory.github.io/Grid-Sampler/" target="_blank" rel="noreferrer">Demo ↗</a></div></div><div className="project-card"><span className="project-index">02</span><strong>HVI-CIDNet</strong><p>HVI color space and low-light enhancement code.</p><div className="project-actions"><a href="https://github.com/Fediory/HVI-CIDNet" target="_blank" rel="noreferrer">Project ↗</a><a href="https://huggingface.co/spaces/Fediory/HVI-CIDNet_Low-light-Image-Enhancement_" target="_blank" rel="noreferrer">Demo ↗</a></div></div><div className="project-card"><span className="project-index">03</span><strong>NPUcore Operating System Kernel Building</strong><p>Team Leader and Teaching Assistant · Sep 2023 – Aug 2024. Built an operating-system kernel and supported featured courses in the Jichang Kang Intelligent System Advanced Class.</p><div className="project-actions"><a href="https://github.com/Fediory/NPUcore-IMPACT" target="_blank" rel="noreferrer">Project ↗</a><span>1st Place · National Finals</span></div></div><div className="project-card"><span className="project-index">04</span><strong>GELLO Software</strong><p>Robot teleoperation framework for low-cost, intuitive control of robot manipulators.</p><div className="project-actions"><a href="https://github.com/Fediory/gello_software" target="_blank" rel="noreferrer">Project ↗</a><span>Robot teleoperation</span></div></div><div className="project-card"><span className="project-index">05</span><strong>LeRobot Piper</strong><p>AgileX Piper adaptation for leader–follower teleoperation, data collection, replay, and policy evaluation.</p><div className="project-actions"><a href="https://github.com/Fediory/lerobot_piper" target="_blank" rel="noreferrer">Project ↗</a><span>Embodied AI systems</span></div></div></div></section>
      </div><footer className="footer"><span>© {new Date().getFullYear()} Yixu Feng (冯宜湑)</span><span>Last updated 2026</span></footer>
    </main>
  );
}
